# Generated by Django 3.0.8 on 2020-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker_app', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hit_points', models.IntegerField()),
                ('card_number', models.CharField(max_length=255)),
                ('total_cards', models.CharField(max_length=255)),
                ('illustrator', models.CharField(max_length=255)),
                ('weakness_amount', models.IntegerField()),
                ('resistance_amount', models.IntegerField()),
                ('retreat_cost', models.IntegerField()),
                ('pokedex_entry', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prevolve_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
