# Generated by Django 3.1.1 on 2020-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker_app', '0004_auto_20200904_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarity',
            name='has_v_style',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
