# Generated by Django 3.1.1 on 2020-09-16 08:52

import card_maker_app.models.card
import card_maker_app.models.user
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker_app', '0005_rarity_has_v_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='over13',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=card_maker_app.models.card.Card.directory_path),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to=card_maker_app.models.card.Card.directory_path),
        ),
        migrations.AlterField(
            model_name='card',
            name='custom_set_image',
            field=models.ImageField(blank=True, null=True, upload_to=card_maker_app.models.card.Card.directory_path),
        ),
        migrations.AlterField(
            model_name='card',
            name='full_card_image',
            field=models.ImageField(upload_to=card_maker_app.models.card.Card.directory_path),
        ),
        migrations.AlterField(
            model_name='card',
            name='prevolve_image',
            field=models.ImageField(blank=True, null=True, upload_to=card_maker_app.models.card.Card.directory_path),
        ),
        migrations.AlterField(
            model_name='card',
            name='top_image',
            field=models.ImageField(blank=True, null=True, upload_to=card_maker_app.models.card.Card.directory_path),
        ),
        migrations.AlterField(
            model_name='card',
            name='type_image',
            field=models.ImageField(blank=True, null=True, upload_to=card_maker_app.models.card.Card.directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default.png', null=True, upload_to=card_maker_app.models.user.User.directory_path),
        ),
    ]
