# Generated by Django 3.1.1 on 2020-09-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker_app', '0007_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
