# Generated by Django 3.1.1 on 2020-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker_app', '0010_auto_20201001_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='public',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
