# Generated by Django 3.1.2 on 2020-10-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker_app', '0016_auto_20201016_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card_maker_app.cardcomment'),
        ),
    ]
