# Generated by Django 3.1.2 on 2020-10-21 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker_app', '0018_auto_20201020_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_admin', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_maker_app.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ban', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card_maker_app_user_ban',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='banned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ban', to='card_maker_app.userban'),
        ),
    ]
