# Generated by Django 3.1.2 on 2020-10-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker_app', '0019_auto_20201021_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userban',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='banned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card_maker_app.userban'),
        ),
    ]
