# Generated by Django 3.1.2 on 2020-10-21 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker_app', '0020_auto_20201021_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userban',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
