# Generated by Django 3.1.2 on 2020-10-21 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_maker_app', '0021_userban_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banned',
        ),
        migrations.AddField(
            model_name='userban',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banned', to='card_maker_app.user'),
            preserve_default=False,
        ),
    ]
